### ISSUE TITLE
Command Injection Vulnerabilities in HTTP Requests

### ISSUE THREAD

**Issue by subho007** [subho007/dvaa#160]
<p>One or more API requests were found to be vulnerable to command injection vulnerabilities</p>

```
1:vapi.appknox.io:80/uptime/s: The time elapsed between the sending of the request and the arrival of the response exceeds the expected amount of time, suggesting a vulnerability to command injection attacks.
confidence: MEDIUM
param:
  location: headers
  method: GET
  variables:
  - User-Agent
  - X-Auth-Token
  - Connection
  - Host
  - Accept-Encoding
severity: HIGH




```
