### ISSUE TITLE
Integer Overflow Vulnerabilities in HTTP Requests

### ISSUE THREAD

**Issue by subho007** [subho007/dvaa#161]
<p>The API may be vulnerable to integer overflow issues</p>

```
1:vapi.appknox.io:80/uptime/s: The time it took to resolve a request with an invalid integer was too long compared to the baseline request. This could indicate a vulnerability to buffer overflow attacks
confidence: LOW
param:
  location: headers
  method: GET
  variables:
  - User-Agent
  - X-Auth-Token
  - Connection
  - Host
  - Accept-Encoding
severity: MEDIUM




```
