### ISSUE TITLE
General Server Vulnerabilities

### ISSUE THREAD

**Issue by subho007** [subho007/dvaa#31]
<p>The API may be susceptible to general server vulnerabilities, which can lead to
further attacks</p>

```
1:vapi.appknox.io:80/tokens: The difference in length between the response to the baseline request and the request returned when sending an attack string exceeds 1000.0 percent, which could indicate a vulnerability to injection attacks
confidence: LOW
param:
  location: data
  method: POST
  type: null
  variables:
  - auth/passwordCredentials/password
  - auth/passwordCredentials/username
severity: LOW

confidence: LOW
param:
  location: headers
  method: POST
  variables:
  - Content-Length
  - User-Agent
  - Accept-Encoding
  - Connection
severity: LOW


vapi.appknox.io:80/tokens: This request returns an error with status code 500, which might indicate some server-side fault that may lead to further vulnerabilities
confidence: HIGH
param:
  location: headers
  method: POST
  variables:
  - Content-Type
severity: LOW

confidence: HIGH
param:
  location: data
  method: POST
  type: null
  variables:
  - auth/passwordCredentials/password
  - auth/passwordCredentials/username
severity: LOW


vapi.appknox.io:80/tokens: This request returns an error with status code 503, which might indicate some server-side fault that may lead to further vulnerabilities
confidence: HIGH
param:
  location: headers
  method: POST
  variables:
  - Content-Type
severity: LOW


vapi.appknox.io:80/tokens: The difference in length between the response to the baseline request and the request returned when sending an attack string exceeds 1000.0 percent, which could indicate a vulnerability to injection attacks
confidence: LOW
param:
  location: data
  method: POST
  type: null
  variables:
  - auth/passwordCredentials/username
  - auth/passwordCredentials/password
severity: LOW

confidence: LOW
param:
  location: headers
  method: POST
  variables:
  - Accept-Encoding
  - User-Agent
  - Content-Length
  - Connection
severity: LOW


vapi.appknox.io:80/tokens: This request returns an error with status code 503, which might indicate some server-side fault that may lead to further vulnerabilities
confidence: HIGH
param:
  location: data
  method: POST
  type: null
  variables:
  - auth/passwordCredentials/username
  - auth/passwordCredentials/password
severity: LOW


vapi.appknox.io:80/tokens: This request returns an error with status code 500, which might indicate some server-side fault that may lead to further vulnerabilities
confidence: HIGH
param:
  location: headers
  method: POST
  variables:
  - Content-Type
severity: LOW

confidence: HIGH
param:
  location: data
  method: POST
  type: null
  variables:
  - auth/passwordCredentials/username
  - auth/passwordCredentials/password
severity: LOW


vapi.appknox.io:80/user: This request returns an error with status code 503, which might indicate some server-side fault that may lead to further vulnerabilities
confidence: HIGH
param:
  location: data
  method: POST
  type: null
  variables:
  - user/password
  - user/username
severity: LOW


vapi.appknox.io:80/user/1: The difference in length between the response to the baseline request and the request returned when sending an attack string exceeds 1000.0 percent, which could indicate a vulnerability to injection attacks
confidence: LOW
param:
  location: headers
  method: GET
  variables:
  - User-Agent
  - Accept-Encoding
  - Connection
  - X-Auth-Token
severity: LOW


vapi.appknox.io:80/user/1: This request returns an error with status code 500, which might indicate some server-side fault that may lead to further vulnerabilities
confidence: HIGH
param:
  location: headers
  method: GET
  variables:
  - X-Auth-Token
severity: LOW


vapi.appknox.io:80/user/1: The difference in length between the response to the baseline request and the request returned when sending an attack string exceeds 1000.0 percent, which could indicate a vulnerability to injection attacks
confidence: LOW
param:
  location: headers
  method: GET
  variables:
  - Accept-Encoding
  - X-Auth-Token
  - Connection
  - User-Agent
severity: LOW


vapi.appknox.io:80/user/1: This request returns an error with status code 500, which might indicate some server-side fault that may lead to further vulnerabilities
confidence: HIGH
param:
  location: headers
  method: GET
  variables:
  - X-Auth-Token
severity: LOW


vapi.appknox.io:80/user: This request returns an error with status code 503, which might indicate some server-side fault that may lead to further vulnerabilities
confidence: HIGH
param:
  location: data
  method: POST
  type: null
  variables:
  - user/username
  - user/password
severity: LOW

confidence: HIGH
param:
  location: headers
  method: POST
  variables:
  - Content-Type
  - Content-Length
severity: LOW




2:vapi.appknox.io:80/user: This request returns an error with status code 503, which might indicate some server-side fault that may lead to further vulnerabilities
confidence: HIGH
param:
  location: data
  method: POST
  type: null
  variables:
  - user/username
  - user/password
severity: LOW

confidence: HIGH
param:
  location: headers
  method: POST
  variables:
  - Content-Length
  - Connection
severity: LOW


vapi.appknox.io:80/tokens: The difference in length between the response to the baseline request and the request returned when sending an attack string exceeds 1000.0 percent, which could indicate a vulnerability to injection attacks
confidence: LOW
param:
  location: data
  method: POST
  type: null
  variables:
  - auth/passwordCredentials/username
  - auth/passwordCredentials/password
severity: LOW

confidence: LOW
param:
  location: headers
  method: POST
  variables:
  - Accept-Encoding
  - Connection
  - User-Agent
  - Content-Length
severity: LOW


vapi.appknox.io:80/tokens: This request returns an error with status code 503, which might indicate some server-side fault that may lead to further vulnerabilities
confidence: HIGH
param:
  location: data
  method: POST
  type: null
  variables:
  - auth/passwordCredentials/username
  - auth/passwordCredentials/password
severity: LOW


vapi.appknox.io:80/tokens: This request returns an error with status code 500, which might indicate some server-side fault that may lead to further vulnerabilities
confidence: HIGH
param:
  location: headers
  method: POST
  variables:
  - Content-Type
severity: LOW

confidence: HIGH
param:
  location: data
  method: POST
  type: null
  variables:
  - auth/passwordCredentials/username
  - auth/passwordCredentials/password
severity: LOW




```
