### ISSUE TITLE
Regex DoS Vulnerabilities in HTTP Requests

### ISSUE THREAD

**Issue by subho007** [subho007/dvaa#33]
<p>Instances of Regex DoS vulnerabilities were found in API requests</p>

```
1:vapi.appknox.io:80/user/1: A response to one of our payload requests has taken too long compared to the baseline request. This could indicate a vulnerability to time-based Regex DoS attacks
confidence: LOW
param:
  location: headers
  method: GET
  variables:
  - X-Auth-Token
  - User-Agent
  - Connection
  - Host
  - Accept-Encoding
severity: MEDIUM




```
