### ISSUE TITLE
SQL Injection Vulnerabilities in HTTP Requests

### ISSUE THREAD

**Issue by subho007** [subho007/dvaa#34]
<p>One or more API requests were found to be vulnerable to SQL injection</p>

```
1:vapi.appknox.io:80/tokens: The string(s): '['syntax error']', known to be commonly returned after a successful SQL injection attack, have been found in the response. This could indicate a vulnerability to SQL injection attacks.
confidence: LOW
param:
  location: data
  method: POST
  type: null
  variables:
  - auth/passwordCredentials/password
  - auth/passwordCredentials/username
severity: MEDIUM


vapi.appknox.io:80/tokens: The string(s): '['syntax error']', known to be commonly returned after a successful SQL injection attack, have been found in the response. This could indicate a vulnerability to SQL injection attacks.
confidence: LOW
param:
  location: data
  method: POST
  type: null
  variables:
  - auth/passwordCredentials/username
  - auth/passwordCredentials/password
severity: MEDIUM


vapi.appknox.io:80/user/1: A response to one of our payload requests has taken too long compared to the baseline request. This could indicate a vulnerability to time-based SQL injection attacks
confidence: LOW
param:
  location: headers
  method: GET
  variables:
  - X-Auth-Token
  - User-Agent
  - Connection
  - Host
  - Accept-Encoding
severity: MEDIUM


vapi.appknox.io:80/user/1: The string(s): '['syntax error']', known to be commonly returned after a successful SQL injection attack, have been found in the response. This could indicate a vulnerability to SQL injection attacks.
confidence: LOW
param:
  location: headers
  method: GET
  variables:
  - X-Auth-Token
severity: MEDIUM


vapi.appknox.io:80/user/1: The string(s): '['syntax error']', known to be commonly returned after a successful SQL injection attack, have been found in the response. This could indicate a vulnerability to SQL injection attacks.
confidence: LOW
param:
  location: headers
  method: GET
  variables:
  - X-Auth-Token
severity: MEDIUM


vapi.appknox.io:80/: A response to one of our payload requests has taken too long compared to the baseline request. This could indicate a vulnerability to time-based SQL injection attacks
confidence: LOW
param:
  location: headers
  method: GET
  variables:
  - User-Agent
  - Accept-Encoding
  - Host
  - Connection
severity: MEDIUM




2:vapi.appknox.io:80/tokens: The string(s): '['syntax error']', known to be commonly returned after a successful SQL injection attack, have been found in the response. This could indicate a vulnerability to SQL injection attacks.
confidence: LOW
param:
  location: data
  method: POST
  type: null
  variables:
  - auth/passwordCredentials/password
  - auth/passwordCredentials/username
severity: MEDIUM




```
