### ISSUE TITLE
Cross-site-scripting Vulnerabilities in HTTP Body

### ISSUE THREAD

**Issue by subho007** [subho007/dvaa#35]
<p>One or more API calls were found to be vulnerable to Cross-Site Scripting (XSS) attacks</p>

```
1:vapi.appknox.io:80/tokens: The string(s): '['<script>alert(document.cookie);</script>']', known to be commonly returned after a successful XSS attack, have been found in the response. This could indicate a vulnerability to XSS attacks.
confidence: LOW
param:
  location: data
  method: POST
  type: null
  variables:
  - auth/passwordCredentials/username
severity: LOW


vapi.appknox.io:80/tokens: The string(s): '['<script>alert(document.cookie);</script>']', known to be commonly returned after a successful XSS attack, have been found in the response. This could indicate a vulnerability to XSS attacks.
confidence: LOW
param:
  location: data
  method: POST
  type: null
  variables:
  - auth/passwordCredentials/username
severity: LOW




2:vapi.appknox.io:80/tokens: The string(s): '['<script>alert(document.cookie);</script>']', known to be commonly returned after a successful XSS attack, have been found in the response. This could indicate a vulnerability to XSS attacks.
confidence: LOW
param:
  location: data
  method: POST
  type: null
  variables:
  - auth/passwordCredentials/username
severity: LOW




```
